# version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # network_mode: "host"
    # depends_on:
    #   mysql-db:
    #     condition: service_healthy
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/finance_tracker
    #   SPRING_DATASOURCE_USERNAME: root
    #   SPRING_DATASOURCE_PASSWORD: root
    #   SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    #   SPRING_JPA_HIBERNATE_DDL-AUTO: update
    networks:
      - spring-network
    # restart: unless-stopped

  # mysql-db:
  #   image: mysql:8.0
  #   container_name: mysql-container
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: finance_tracker
  #     MYSQL_USERNAME: root
  #     MYSQL_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - spring-network
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s


  react-app:
    build:
      context: ./finance-tracker-frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - spring-app
    networks:
      - spring-network
    # extra_hosts:
    #   - "spring-app:host.docker.internal"

networks:
  spring-network:

# volumes:
#   db_data: